cors:
 originPatterns: http://localhost:8080,http://localhost:3000
security:
  jwt:
    token:
      secret-key: 53ccr37
      expire-lenght: 3600000
file:
  upload-dir: /Users/rafad/uploadDir
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
  servelet: 
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB 
spring-doc:
 pathsToMatch: 
   - /api/**/v1/**
   - /auth/**
 swagger-ui:
   use-root-path: true